from .FisherDiscriminantAnalysis import FisherDiscriminantAnalysis
from .GaussianDiscriminantAnalysis import GaussianDiscriminantAnalysis
from .LinearDiscriminantAnalysis import LinearDiscriminantAnalysis